using Dapper;
using Npgsql;
using Testcontainers.PostgreSql;
using Themia.Data.Migrations;
using Xunit;

namespace Themia.Migrations.ReplayTests;

/// <summary>
/// coord #0085, reproduced: a 0.15 consumer that created <c>data_protection_keys</c> with its OWN
/// FluentMigrator migrations, so Themia's migration never executed there, then upgrades to 0.16 and
/// meets an empty per-assembly ledger.
/// </summary>
/// <remarks>
/// <see cref="MigrationReplayTestsBase.Applying_twice_is_safe"/> covers the case where THEMIA created the
/// object and replays over its own work. It cannot cover this one: there the table came from Themia's own
/// migration, so any guard that merely agrees with what Themia just did passes. Here the table predates
/// Themia entirely and carries a consumer's shape.
/// </remarks>
[Trait("Category", "Integration")]
public sealed class ConsumerOwnedTableUpgradeTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer container =
        new PostgreSqlBuilder("postgres:16-alpine").WithCleanUp(true).Build();

    private string ConnectionString => container.GetConnectionString();

    [Fact]
    public async Task Themia_adopts_a_data_protection_keys_table_the_consumer_created()
    {
        await using (var seed = new NpgsqlConnection(ConnectionString))
        {
            // The consumer's own migration ledger and its own DDL — neither of which Themia wrote.
            await seed.ExecuteAsync(
                "CREATE TABLE \"VersionInfo\" (\"Version\" bigint NOT NULL, \"AppliedOn\" timestamp NULL, "
                + "\"Description\" varchar(1024) NULL)");
            await seed.ExecuteAsync(
                "INSERT INTO \"VersionInfo\" (\"Version\", \"AppliedOn\", \"Description\") VALUES "
                + "(202607260001, @Now, 'consumer migration that collided with Themia''s'), "
                + "(202607290001, @Now, 'M202607290001_CreateDataProtectionKeysTable'), "
                + "(202608020002, @Now, 'M202608020002_WidenDataProtectionKeysIdToBigint')",
                new { Now = DateTime.UtcNow });

            await seed.ExecuteAsync(
                "CREATE TABLE data_protection_keys ("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "friendly_name varchar(512) NULL, "
                + "xml text NOT NULL, "
                + "created_at timestamp NOT NULL)");
            await seed.ExecuteAsync(
                "INSERT INTO data_protection_keys (friendly_name, xml, created_at) "
                + "VALUES ('key-1', '<key/>', @Now)", new { Now = DateTime.UtcNow });
        }

        var assembly = typeof(AspNetCore.DataProtection.ThemiaXmlRepository).Assembly;
        ThemiaMigrations.Run(MigrationEngine.Postgres, ConnectionString, assembly);

        await using var connection = new NpgsqlConnection(ConnectionString);

        // The consumer's row survived: the table was adopted, not recreated.
        var keys = await connection.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM data_protection_keys");
        Assert.Equal(1, keys);

        // And the adoption was recorded, so the next boot has nothing pending. Without this the guard
        // would still pass every time while the migration stayed forever unapplied.
        var ledger = new ThemiaVersionTable(assembly).TableName;
        var recorded = await connection.ExecuteScalarAsync<int>(
            $"SELECT COUNT(*) FROM \"{ledger}\" WHERE \"Version\" = 202607260001");
        Assert.Equal(1, recorded);
    }

    public Task InitializeAsync() => container.StartAsync();

    public Task DisposeAsync() => container.DisposeAsync().AsTask();
}
