//HintName: ThemiaServiceRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Themia.Extensions;

namespace Themia.Generated;

public static class ThemiaServiceRegistrations
{
    public static IServiceCollection AddThemiaServices(this IServiceCollection services)
    {

        services.AddScoped<global::Demo.ICustomerRepository, global::Demo.CustomerRepository>();

        return services;
    }
}
