//HintName: ThemiaServiceRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace Themia.Generated;

public static class ThemiaServiceRegistrations
{
    public static IServiceCollection AddThemiaServices(this IServiceCollection services)
    {

        services.AddScoped<global::Demo.IAlphaRepository, global::Demo.AlphaRepository>();
        services.AddScoped<global::Demo.IMidRepository, global::Demo.MidRepository>();
        services.AddScoped<global::Demo.IZetaRepository, global::Demo.ZetaRepository>();

        return services;
    }
}
