//HintName: ThemiaServiceRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace Themia.Generated;

internal static class ThemiaServiceRegistrations
{
    public static IServiceCollection AddThemiaServices(this IServiceCollection services)
    {

        services.AddKeyedScoped<global::Demo.IPaymentGateway, global::Demo.PrimaryGateway>("primary");

        return services;
    }
}
