//HintName: ThemiaServiceRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace Themia.Generated;

public static class ThemiaServiceRegistrations
{
    public static IServiceCollection AddThemiaServices(this IServiceCollection services)
    {

        new global::Demo.MyRegistrar().Register(services);

        return services;
    }
}
