using Themia.Generators.Abstractions.Emission;
using Xunit;

namespace Themia.Generators.Abstractions.Tests.Emission;

public class ThemiaSourceWriterTests
{
    [Fact]
    public void EmptyWriter_ProducesEmptyText()
    {
        var w = new ThemiaSourceWriter();
        Assert.Equal("", w.ToSourceText().ToString());
    }

    [Fact]
    public void Header_AddsAutoGeneratedComment()
    {
        var w = new ThemiaSourceWriter().WithFileHeader();
        var text = w.ToSourceText().ToString();
        Assert.Contains("<auto-generated/>", text);
        Assert.Contains("#nullable enable", text);
    }

    [Fact]
    public void Namespace_RendersFileScopedNamespace()
    {
        var w = new ThemiaSourceWriter().WithNamespace("Foo.Bar");
        Assert.Contains("namespace Foo.Bar;", w.ToSourceText().ToString());
    }

    [Fact]
    public void Usings_DeduplicatesAndSortsAlphabetically()
    {
        var w = new ThemiaSourceWriter().WithUsings("Z", "A", "M", "A");
        var text = w.ToSourceText().ToString();
        var idxA = text.IndexOf("using A;");
        var idxM = text.IndexOf("using M;");
        var idxZ = text.IndexOf("using Z;");
        Assert.True(idxA < idxM && idxM < idxZ);
        Assert.Equal(1, CountOccurrences(text, "using A;"));
    }

    [Fact]
    public void OpenClass_OpenMethod_AppendLine_NestsCorrectly()
    {
        var text = new ThemiaSourceWriter()
            .WithNamespace("X")
            .OpenClass("MyClass", isStatic: true)
            .OpenMethod("public static void M()")
            .AppendLine("var x = 1;")
            .CloseMethod()
            .CloseClass()
            .ToSourceText().ToString();

        Assert.Contains("public static class MyClass", text);
        Assert.Contains("public static void M()", text);
        Assert.Contains("var x = 1;", text);
    }

    private static int CountOccurrences(string s, string needle)
    {
        int count = 0, i = 0;
        while ((i = s.IndexOf(needle, i, System.StringComparison.Ordinal)) != -1) { count++; i += needle.Length; }
        return count;
    }
}
