// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Themia.Modules.Scheduling;

#nullable disable

namespace Themia.Modules.Scheduling.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20260607003329_InitialScheduling")]
    partial class InitialScheduling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Themia.Modules.Scheduling.ExecutionHistoryRecord", b =>
                {
                    b.Property<string>("FireInstanceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fire_instance_id");

                    b.Property<DateTimeOffset>("ActualFireTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_fire_time_utc");

                    b.Property<string>("ExceptionMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("exception_message");

                    b.Property<DateTimeOffset?>("FinishedTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_time_utc");

                    b.Property<string>("Job")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("job");

                    b.Property<bool>("Recovering")
                        .HasColumnType("boolean")
                        .HasColumnName("recovering");

                    b.Property<DateTimeOffset?>("ScheduledFireTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_fire_time_utc");

                    b.Property<string>("SchedulerInstanceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("scheduler_instance_id");

                    b.Property<string>("SchedulerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("scheduler_name");

                    b.Property<string>("Trigger")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("trigger");

                    b.Property<bool>("Vetoed")
                        .HasColumnType("boolean")
                        .HasColumnName("vetoed");

                    b.HasKey("FireInstanceId")
                        .HasName("pk_execution_history");

                    b.HasIndex("SchedulerName", "Trigger", "ActualFireTimeUtc")
                        .HasDatabaseName("ix_execution_history_scheduler_trigger_fired");

                    b.ToTable("execution_history", "scheduling");
                });

            modelBuilder.Entity("Themia.Modules.Scheduling.SchedulerStatsRecord", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("scheduler_name");

                    b.Property<int>("TotalJobsExecuted")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs_executed");

                    b.Property<int>("TotalJobsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs_failed");

                    b.HasKey("SchedulerName")
                        .HasName("pk_scheduler_stats");

                    b.ToTable("scheduler_stats", "scheduling");
                });
#pragma warning restore 612, 618
        }
    }
}
