using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Themia.Generators.Abstractions.Emission;

/// <summary>
/// Fluent C# source builder used by Themia source generators. Manages
/// indentation, namespace scope, usings deduplication, and class/method
/// opening/closing. Output is deterministic — equal inputs always produce
/// equal output, suitable for snapshot testing.
/// </summary>
public sealed class ThemiaSourceWriter
{
    private readonly List<string> _lines = [];
    private readonly SortedSet<string> _usings = new(StringComparer.Ordinal);
    private bool _includeFileHeader;
    private string? _namespace;
    private int _indent;
    private readonly Stack<string> _scopeStack = new();

    /// <summary>Adds the auto-generated file header comment and nullable enable directive.</summary>
    public ThemiaSourceWriter WithFileHeader()
    {
        _includeFileHeader = true;
        return this;
    }

    /// <summary>Sets the file-scoped namespace for the generated source.</summary>
    public ThemiaSourceWriter WithNamespace(string ns)
    {
        if (string.IsNullOrEmpty(ns)) throw new ArgumentException("Namespace cannot be empty", nameof(ns));
        _namespace = ns;
        return this;
    }

    /// <summary>Adds using directives, deduplicating across multiple calls.</summary>
    public ThemiaSourceWriter WithUsings(params string[] namespaces)
    {
        foreach (var ns in namespaces)
        {
            if (!string.IsNullOrEmpty(ns)) _usings.Add(ns);
        }
        return this;
    }

    /// <summary>Emits a class declaration and opens its scope.</summary>
    /// <param name="name">The class name.</param>
    /// <param name="isStatic">When <see langword="true"/>, emits the <c>static</c> modifier.</param>
    /// <param name="isPartial">When <see langword="true"/>, emits the <c>partial</c> modifier.</param>
    /// <param name="isInternal">When <see langword="true"/>, emits <c>internal</c> accessibility; otherwise <c>public</c>.</param>
    public ThemiaSourceWriter OpenClass(string name, bool isStatic = false, bool isPartial = false, bool isInternal = false)
    {
        var accessibility = isInternal ? "internal" : "public";
        var modifiers = (isStatic ? "static " : "") + (isPartial ? "partial " : "");
        AppendIndentedLine($"{accessibility} {modifiers}class {name}");
        AppendIndentedLine("{");
        _indent++;
        _scopeStack.Push("class");
        return this;
    }

    /// <summary>Closes the current class scope.</summary>
    public ThemiaSourceWriter CloseClass()
    {
        if (_scopeStack.Count == 0 || _scopeStack.Peek() != "class")
            throw new InvalidOperationException("CloseClass called without matching OpenClass.");
        _indent--;
        AppendIndentedLine("}");
        _scopeStack.Pop();
        return this;
    }

    /// <summary>Emits a method signature and opens its scope.</summary>
    public ThemiaSourceWriter OpenMethod(string signature)
    {
        AppendIndentedLine(signature);
        AppendIndentedLine("{");
        _indent++;
        _scopeStack.Push("method");
        return this;
    }

    /// <summary>Closes the current method scope.</summary>
    public ThemiaSourceWriter CloseMethod()
    {
        if (_scopeStack.Count == 0 || _scopeStack.Peek() != "method")
            throw new InvalidOperationException("CloseMethod called without matching OpenMethod.");
        _indent--;
        AppendIndentedLine("}");
        _scopeStack.Pop();
        return this;
    }

    /// <summary>Appends an indented line of source text.</summary>
    public ThemiaSourceWriter AppendLine(string line = "")
    {
        AppendIndentedLine(line);
        return this;
    }

    /// <summary>Appends a raw (non-indented) line of source text.</summary>
    public ThemiaSourceWriter AppendRaw(string raw)
    {
        _lines.Add(raw);
        return this;
    }

    /// <summary>Renders the accumulated source into a <see cref="SourceText"/>.</summary>
    public SourceText ToSourceText()
    {
        if (_scopeStack.Count != 0)
            throw new InvalidOperationException(
                $"Cannot render: {_scopeStack.Count} scope(s) left open; every OpenClass/OpenMethod needs a matching Close.");

        var sb = new StringBuilder();
        if (_includeFileHeader)
        {
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
        }

        foreach (var u in _usings) sb.AppendLine($"using {u};");
        if (_usings.Count > 0) sb.AppendLine();

        if (!string.IsNullOrEmpty(_namespace))
        {
            sb.AppendLine($"namespace {_namespace};");
            sb.AppendLine();
        }

        foreach (var line in _lines) sb.AppendLine(line);

        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    private void AppendIndentedLine(string line)
    {
        if (line.Length == 0) _lines.Add("");
        else _lines.Add(new string(' ', _indent * 4) + line);
    }
}
