using Dapper;
using Microsoft.Extensions.DependencyInjection;
using Npgsql;
using Testcontainers.PostgreSql;
using Themia.Content.DependencyInjection;
using Themia.Content.PostgreSql;
using Xunit;

namespace Themia.Content.IntegrationTests;

[Trait("Category", "Integration")]
public sealed class PropertiezyAdoptionTests : IAsyncLifetime
{
    private const string CounselTerms = "# ข้อกำหนดการใช้บริการ\n\nข้อความที่ทนายตรวจแล้ว";
    private const string SeedPlaceholder = "# ข้อกำหนดการใช้บริการ\n\n[placeholder]";

    private readonly PostgreSqlContainer container = new PostgreSqlBuilder("postgres:16-alpine").Build();

    public Task InitializeAsync() => container.StartAsync();

    public Task DisposeAsync() => container.DisposeAsync().AsTask();

    [Fact]
    public async Task ExistingPropertiezyDatabase_ShouldAdoptWithoutChangingItsTables_AndImportOnlyAfterTheRevisionFix()
    {
        var connectionString = container.GetConnectionString();
        await using var db = new NpgsqlConnection(connectionString);
        await db.OpenAsync();

        // 1. propertiezy's schema and data, as its migrations leave them.
        await db.ExecuteAsync(PropertiezySchema);
        await db.ExecuteAsync(PropertiezyRows, new { CounselTerms, SeedPlaceholder });
        var before = await SnapshotAsync(db);

        // 2. Themia registers against the same database: its migration meets tables it did not create.
        using var provider = new ServiceCollection()
            .AddThemiaContent(o => { o.Languages.Add("th"); o.Languages.Add("en"); o.FallbackLanguage = "th"; })
            .AddThemiaContentPostgres(connectionString)
            .BuildServiceProvider();
        var importer = provider.GetRequiredService<IContentPageImporter>();
        var service = provider.GetRequiredService<IContentPageService>();

        Assert.Equal(before, await SnapshotAsync(db));
        Assert.True(await db.ExecuteScalarAsync<bool>("SELECT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'content_pages');"));

        // 3. Import through the README recipe: refused, naming only the page whose served text is in no revision.
        var refused = await importer.ImportAsync(await PropertiezyRecipe.ReadAsync(db));
        Assert.Equal(ContentImportOutcome.Invalid, refused.Outcome);
        var violation = Assert.Single(refused.Violations);
        Assert.Equal(("terms", "th", ContentImportRule.ContentDiffersFromCurrentRevision), (violation.Slug, violation.Language, violation.Rule));
        Assert.Equal(0, await db.ExecuteScalarAsync<long>("SELECT COUNT(*) FROM content_pages;"));

        // 4. The fix propertiezy was given in coord #0132, marked "NOT RUN" there.
        await db.ExecuteAsync(RecordServedContentAsRevision);
        var afterFix = await SnapshotAsync(db);

        // 5. Import again: everything, and propertiezy's tables are untouched by it.
        var imported = await importer.ImportAsync(await PropertiezyRecipe.ReadAsync(db));
        Assert.Equal(ContentImportOutcome.Imported, imported.Outcome);
        Assert.Equal((2, 4), (imported.ImportedPages, imported.ImportedRevisions));
        Assert.Equal(afterFix, await SnapshotAsync(db));

        // 6. Readers get counsel's text byte for byte, and the revert that served the placeholder now cannot.
        Assert.Equal(CounselTerms, (await service.GetPublishedAsync("terms", "th"))!.Markdown);
        var revisions = await service.GetRevisionsAsync("terms", "th", 1, 20);
        Assert.Equal(CounselTerms, revisions.Items.Single(r => r.Version == 2).Markdown);
    }

    private static async Task<string> SnapshotAsync(NpgsqlConnection db)
    {
        var pages = await db.QueryAsync<string>("""SELECT row_to_json(t)::text FROM "CmsPages" t ORDER BY "CmsPageId";""");
        var revisions = await db.QueryAsync<string>("""SELECT row_to_json(t)::text FROM "CmsPageRevisions" t ORDER BY "CmsPageRevisionId";""");
        return string.Join("\n", pages.Concat(revisions));
    }

    private const string PropertiezySchema = """
        CREATE TABLE "CmsPages" (
            "CmsPageId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Slug" varchar(100) NOT NULL,
            "Title" varchar(200) NOT NULL,
            "ContentMarkdown" text NOT NULL,
            "CurrentVersion" integer NOT NULL DEFAULT 1,
            "IsPublished" boolean NOT NULL DEFAULT true,
            "InsertDate" timestamptz NOT NULL DEFAULT now(),
            "UpdateDate" timestamptz NOT NULL DEFAULT now(),
            "UpdateUserId" uuid NULL,
            "Language" varchar(2) NOT NULL DEFAULT 'th',
            CONSTRAINT "UC_CmsPages_Slug_Language" UNIQUE ("Slug", "Language"));
        CREATE TABLE "CmsPageRevisions" (
            "CmsPageRevisionId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CmsPageId" integer NOT NULL REFERENCES "CmsPages" ("CmsPageId") ON DELETE CASCADE,
            "Version" integer NOT NULL,
            "Title" varchar(200) NOT NULL,
            "ContentMarkdown" text NOT NULL,
            "ChangeSummary" varchar(500) NULL,
            "CreatedUserId" uuid NULL,
            "CreatedDate" timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT "UC_CmsPageRevisions_Page_Version" UNIQUE ("CmsPageId", "Version"));
        """;

    // terms/th: seeded at version 1, then its served text replaced by a content migration without a revision.
    // privacy/en: two consistent revisions, as an editor produces them.
    private const string PropertiezyRows = """
        INSERT INTO "CmsPages" ("Slug", "Language", "Title", "ContentMarkdown", "CurrentVersion", "IsPublished", "InsertDate", "UpdateDate")
        VALUES ('terms', 'th', 'ข้อกำหนด', @CounselTerms, 1, true, '2026-08-19T02:00:00Z', '2026-09-12T07:57:00Z');
        INSERT INTO "CmsPageRevisions" ("CmsPageId", "Version", "Title", "ContentMarkdown", "CreatedDate")
        VALUES (1, 1, 'ข้อกำหนด', @SeedPlaceholder, '2026-08-19T02:00:00Z');
        INSERT INTO "CmsPages" ("Slug", "Language", "Title", "ContentMarkdown", "CurrentVersion", "IsPublished", "InsertDate", "UpdateDate", "UpdateUserId")
        VALUES ('privacy', 'en', 'Privacy', '# Privacy v2', 2, true, '2026-08-19T02:00:00Z', '2026-09-12T06:34:00Z', '4d9e1b2c-0000-0000-0000-000000000002');
        INSERT INTO "CmsPageRevisions" ("CmsPageId", "Version", "Title", "ContentMarkdown", "CreatedUserId", "CreatedDate")
        VALUES (2, 1, 'Privacy', '# Privacy v1', '4d9e1b2c-0000-0000-0000-000000000001', '2026-08-19T02:00:00Z'),
               (2, 2, 'Privacy', '# Privacy v2', '4d9e1b2c-0000-0000-0000-000000000002', '2026-09-12T06:34:00Z');
        """;

    // Verbatim from coord #0132's example.
    private const string RecordServedContentAsRevision = """
        INSERT INTO "CmsPageRevisions" ("CmsPageId", "Version", "Title", "ContentMarkdown", "ChangeSummary", "CreatedDate")
        SELECT p."CmsPageId", p."CurrentVersion" + 1, p."Title", p."ContentMarkdown",
               'Content set by a migration, recorded as a revision', NOW()
          FROM "CmsPages" p
          JOIN "CmsPageRevisions" r ON r."CmsPageId" = p."CmsPageId" AND r."Version" = p."CurrentVersion"
         WHERE r."Title" IS DISTINCT FROM p."Title"
            OR r."ContentMarkdown" IS DISTINCT FROM p."ContentMarkdown";

        UPDATE "CmsPages" p
           SET "CurrentVersion" = p."CurrentVersion" + 1
         WHERE EXISTS (SELECT 1 FROM "CmsPageRevisions" r
                        WHERE r."CmsPageId" = p."CmsPageId" AND r."Version" = p."CurrentVersion" + 1);
        """;
}

/// <summary>The README's recipe for reading propertiezy's tables into import records. Consumer code: it names the
/// consumer's tables, so it lives here and in the README, never in the package.</summary>
internal static class PropertiezyRecipe
{
    private const string PagesSql = """
        SELECT "Slug", "Language", "Title", "ContentMarkdown", "CurrentVersion", "IsPublished", "InsertDate", "UpdateDate", "UpdateUserId"
          FROM "CmsPages" ORDER BY "CmsPageId";
        """;

    private const string RevisionsSql = """
        SELECT p."Slug", p."Language", r."Version", r."Title", r."ContentMarkdown", r."ChangeSummary", r."CreatedUserId", r."CreatedDate"
          FROM "CmsPageRevisions" r JOIN "CmsPages" p ON p."CmsPageId" = r."CmsPageId"
         ORDER BY p."CmsPageId", r."Version";
        """;

    public static async Task<IReadOnlyList<ContentPageImport>> ReadAsync(NpgsqlConnection db)
    {
        var pages = await db.QueryAsync<PageRow>(PagesSql);
        var revisions = (await db.QueryAsync<RevisionRow>(RevisionsSql)).ToLookup(r => (r.Slug, r.Language));

        return pages.Select(p => new ContentPageImport(
                p.Slug, p.Language, p.Title, p.ContentMarkdown, p.CurrentVersion, p.IsPublished,
                p.InsertDate, p.UpdateDate, p.UpdateUserId?.ToString(),
                revisions[(p.Slug, p.Language)]
                    .Select(r => new ContentRevisionImport(r.Version, r.Title, r.ContentMarkdown, r.ChangeSummary, r.CreatedUserId?.ToString(), r.CreatedDate))
                    .ToList()))
            .ToList();
    }

    private sealed class PageRow
    {
        public string Slug { get; set; } = string.Empty;
        public string Language { get; set; } = string.Empty;
        public string Title { get; set; } = string.Empty;
        public string ContentMarkdown { get; set; } = string.Empty;
        public int CurrentVersion { get; set; }
        public bool IsPublished { get; set; }
        public DateTimeOffset InsertDate { get; set; }
        public DateTimeOffset UpdateDate { get; set; }
        public Guid? UpdateUserId { get; set; }
    }

    private sealed class RevisionRow
    {
        public string Slug { get; set; } = string.Empty;
        public string Language { get; set; } = string.Empty;
        public int Version { get; set; }
        public string Title { get; set; } = string.Empty;
        public string ContentMarkdown { get; set; } = string.Empty;
        public string? ChangeSummary { get; set; }
        public Guid? CreatedUserId { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
    }
}
