#nullable enable
using System.Collections.Immutable;
using System.Text;
using Themia.SourceGenerator.Models;
using Themia.SourceGenerator.Utilities;

namespace Themia.SourceGenerator.Generators;

/// <summary>
/// Builds source code for generated mediator handlers.
/// </summary>
internal static class SourceBuilder
{
    /// <summary>
    /// Builds source for a single handler (registration + invoker).
    /// </summary>
    public static string BuildPerHandler(HandlerModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Themia.Mediator.Abstractions;");
        sb.AppendLine("using Themia.Mediator.Pipelines;");
        sb.AppendLine();
        sb.AppendLine("namespace Themia.Mediator.Generated;");
        sb.AppendLine();

        // Debug info
        var attrs = model.HandlerType.GetAttributes();
        sb.AppendLine($"// DEBUG: Handler {model.HandlerType.Name} has Lifetime={model.Lifetime}");
        sb.AppendLine($"// DEBUG: Handler has {attrs.Length} attributes:");
        foreach (var attr in attrs)
        {
            var attrName = attr.AttributeClass?.Name ?? "null";
            var fullName = attr.AttributeClass?.ToDisplayString() ?? "null";
            sb.AppendLine($"//   - {attrName} (full: {fullName})");
            sb.AppendLine($"//     ConstructorArgs: {attr.ConstructorArguments.Length}");
            foreach (var arg in attr.ConstructorArguments)
            {
                sb.AppendLine($"//       [{arg.Type}] = {arg.Value}");
            }
            sb.AppendLine($"//     NamedArgs: {attr.NamedArguments.Length}");
            foreach (var arg in attr.NamedArguments)
            {
                sb.AppendLine($"//       {arg.Key} = {arg.Value.Value}");
            }
        }

        sb.AppendLine("internal static partial class MediatorGenerated");
        sb.AppendLine("{");

        // Generate registration method
        var lifetimeMethod = model.Lifetime switch
        {
            ServiceLifetime.Singleton => "AddSingleton",
            ServiceLifetime.Scoped => "AddScoped",
            ServiceLifetime.Transient => "AddTransient",
            _ => "AddScoped"
        };

        var handlerInterface = model.Kind switch
        {
            HandlerKind.Command => "ICommandHandler",
            HandlerKind.Query => "IQueryHandler",
            HandlerKind.Request => "IRequestHandler",
            _ => "IRequestHandler"
        };

        sb.AppendLine($"    internal static void Add_{model.SafeHintName}(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.{lifetimeMethod}<{handlerInterface}<{model.RequestType.GetFullyQualifiedName()}, {model.ResponseType.GetFullyQualifiedName()}>, {model.HandlerType.GetFullyQualifiedName()}>();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate invoker delegate
        sb.AppendLine($"    internal static readonly global::System.Func<global::System.IServiceProvider, object?, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<object?>> Invoke_{model.SafeHintName} =");
        sb.AppendLine("        static async (sp, req, ct) =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var request = ({model.RequestType.GetFullyQualifiedName()})req!;");
        sb.AppendLine($"            var handler = sp.GetRequiredService<{handlerInterface}<{model.RequestType.GetFullyQualifiedName()}, {model.ResponseType.GetFullyQualifiedName()}>>();");
        sb.AppendLine();
        sb.AppendLine("            // Compose pipeline behaviors");
        sb.AppendLine($"            var behaviors = sp.GetServices<global::Themia.Mediator.Abstractions.IPipelineBehavior<{model.RequestType.GetFullyQualifiedName()}, {model.ResponseType.GetFullyQualifiedName()}>>().Reverse();");
        sb.AppendLine($"            global::Themia.Mediator.Pipelines.RequestHandlerContinuation<{model.ResponseType.GetFullyQualifiedName()}> pipeline = (ct2) => handler.HandleAsync(request, ct2);");
        sb.AppendLine();
        sb.AppendLine("            foreach (var behavior in behaviors)");
        sb.AppendLine("            {");
        sb.AppendLine("                var currentBehavior = behavior;");
        sb.AppendLine("                var currentPipeline = pipeline;");
        sb.AppendLine("                pipeline = (ct2) => currentBehavior.HandleAsync(request, currentPipeline, ct2);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var result = await pipeline(ct).ConfigureAwait(false);");
        sb.AppendLine("            return (object?)result;");
        sb.AppendLine("        };");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Builds aggregated registration extension method.
    /// </summary>
    public static string BuildRegistration(ImmutableArray<HandlerModel> handlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Themia.Mediator.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods for registering generated mediator handlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class MediatorHandlerRegistrationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Registers the mediator dispatcher and {handlers.Length} generated handler(s) with the service collection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedMediatorHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Register the generated mediator dispatcher");
        sb.AppendLine("        services.AddScoped<global::Themia.Mediator.Abstractions.IMediator, global::Themia.Mediator.MediatorDispatcher>();");
        sb.AppendLine();

        foreach (var handler in handlers)
        {
            sb.AppendLine($"        MediatorGenerated.Add_{handler.SafeHintName}(services);");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Builds reflection-free dispatcher.
    /// </summary>
    public static string BuildDispatcher(ImmutableArray<HandlerModel> handlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Themia.Mediator.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace Themia.Mediator;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated mediator dispatcher with compile-time handler resolution.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed class MediatorDispatcher : IMediator");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine($"    private static readonly global::System.Collections.Generic.IReadOnlyDictionary<global::System.Type, global::System.Func<global::System.IServiceProvider, object?, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<object?>>> _dispatchMap = CreateDispatchMap();");
        sb.AppendLine();
        sb.AppendLine("    public MediatorDispatcher(global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serviceProvider = serviceProvider ?? throw new global::System.ArgumentNullException(nameof(serviceProvider));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public async global::System.Threading.Tasks.Task<TResponse> SendAsync<TResponse>(IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (request is null)");
        sb.AppendLine("            throw new global::System.ArgumentNullException(nameof(request));");
        sb.AppendLine();
        sb.AppendLine("        var requestType = request.GetType();");
        sb.AppendLine("        if (_dispatchMap.TryGetValue(requestType, out var invoker))");
        sb.AppendLine("        {");
        sb.AppendLine("            var result = await invoker(_serviceProvider, request, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            return (TResponse)result!;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        throw new global::System.InvalidOperationException($\"No handler registered for request type '{requestType.FullName}'. Ensure the assembly containing the handler has [assembly: GenerateMediatorHandlers] attribute.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    private static global::System.Collections.Generic.IReadOnlyDictionary<global::System.Type, global::System.Func<global::System.IServiceProvider, object?, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<object?>>> CreateDispatchMap()");
        sb.AppendLine("    {");
        sb.AppendLine($"        var map = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<global::System.IServiceProvider, object?, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<object?>>>({handlers.Length});");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"        map[typeof({handler.RequestType.GetFullyQualifiedName()})] = Generated.MediatorGenerated.Invoke_{handler.SafeHintName};");
        }

        sb.AppendLine("        return map;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
