using System.Text.Json;

using Xunit;

namespace Themia.Messaging.Hmac.Tests;

// The "candidate" vector below is generated by Themia itself, not transcribed from a peer fixture.
// It has NOT been confirmed by propertiezy or ezy-assets and must never be folded into
// GoldenVectorTests.Confirmed() — that is why it lives in its own class: a failure here means "our own
// generated pin drifted," never "the live interop contract broke."
public class CandidateVectorTests
{
    private const string ExpectedName = "lead-post-thai-multiline-body";
    private const string ExpectedSignature = "a1f0e020f882b90640cc5f88816186aaaf34156ca894fed53c5bb2cbc06561e8";

    private static GoldenVectorTests.Vector LoadCandidate()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Vectors", "golden-vectors.json");
        using var stream = File.OpenRead(path);
        using var doc = JsonDocument.Parse(stream);
        var element = doc.RootElement.GetProperty("vectors").EnumerateArray()
            .Single(e => e.GetProperty("status").GetString() == "candidate");

        return new GoldenVectorTests.Vector(
            element.GetProperty("name").GetString()!,
            element.GetProperty("status").GetString()!,
            element.GetProperty("secret").GetString()!,
            element.GetProperty("timestamp").GetString()!,
            element.GetProperty("method").GetString()!,
            element.GetProperty("pathAndQuery").GetString()!,
            element.GetProperty("body").GetString()!,
            element.GetProperty("signature").GetString()!);
    }

    [Fact]
    public void Vectors_ShouldContainExactlyOneCandidate()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Vectors", "golden-vectors.json");
        using var stream = File.OpenRead(path);
        using var doc = JsonDocument.Parse(stream);

        var candidateCount = doc.RootElement.GetProperty("vectors").EnumerateArray()
            .Count(e => e.GetProperty("status").GetString() == "candidate");

        Assert.Equal(1, candidateCount);
    }

    [Fact]
    public void Candidate_Body_ShouldRoundTrip_WithExactlyOneLiteralNewline_AndThaiCharactersIntact()
    {
        var candidate = LoadCandidate();

        Assert.Equal(ExpectedName, candidate.Name);
        Assert.Equal(1, candidate.Body.Count(c => c == '\n'));
        Assert.DoesNotContain("\\n", candidate.Body, StringComparison.Ordinal);
        Assert.Contains("สมชาย ใจดี", candidate.Body, StringComparison.Ordinal);
        Assert.Contains("บรรทัดแรก\nบรรทัดที่สอง", candidate.Body, StringComparison.Ordinal);
    }

    [Fact]
    public void Candidate_ShouldSignToItsRecordedSignature()
    {
        var candidate = LoadCandidate();
        var canonical = ThemiaHmacV1.Canonicalize(
            candidate.Timestamp, candidate.Method, candidate.PathAndQuery, candidate.Body);

        Assert.Equal(ExpectedSignature, ThemiaHmacV1.Sign(canonical, candidate.Secret));
        Assert.Equal(ExpectedSignature, candidate.Signature);
    }
}
